---
title: "Day 4 Comp Session 1"
format: html
editor: visual
---

## Making Vectors 

```{r}

#c is concatenate  give it a series of values
rain <- c(3, 5, 10.1, 6)


#scalar multiplication
rain_scaled <- 5* rain


```

## Making matrices

```{r}
#make a sequence of values and then wrap those values into a matrix, one long vector and populate a 3 by 5 matrix with those values, row by row.
#seq needs two things, start value and end value

my_values <- seq(from = 1, to=10 )

#wrapping this into a 2 by 5 matrix by saying:
#know what direction it is populating in , populating by column first byrow=false but it is the default

my_matrix <-matrix(data = my_values, nrow=2, ncol=5, byrow= TRUE)
```

```{r}
my_matrix2 <- matrix(data= my_values, nrow=3, ncol=4, byrow= TRUE)

#warning says we don't have a complete set of multiples of our original sequence, then it starts repeating. 
```

```{r}
matrixA <- matrix(data = seq( from =2, to =5, length =10),
                  nrow= 2,
                  ncol=5,
                  byrow= TRUE)
```

Matrix addition/subtraction

```{r}
my_matrix + matrixA
```

## Matrix multiplication

```{r}
#make two matrices, both 2 by 2
cats <- matrix(data = c(0, 4, 3, 1),
               nrow=2,
               ncol =2,
               byrow =TRUE)
dogs <- matrix(data =c(-6, -3, 0, 2),
               nrow=2,
               ncol=2,
               byrow= TRUE)

```

```{r}
dogs %*% cats
```

## Leslie Matrix example

making a matrix of coefficients, providing initial conditions

```{r}
insec_leslie <- matrix (data= c(0, 0, 600, 0.2, 0, 0, 0, 0.08, 0),
                        nrow=3,
                        ncol=3,
                        byrow=TRUE)
#giving intial condition 

insect_y0 <- c(12000, 700, 500)
#second matrix which will take the dot product with 

```

Find the population structure for each live stage at t=1 year:

```{r}
#find the dot product, multiply matrix of coefficient

insect_y1 <- insec_leslie %*% insect_y0

#600 eggs multiplied by initial adult female 300,000 eggs in the next cycle 

```

Find the population structure at t=2 years:

```{r}
insect_y2 <- insec_leslie %*% insect_y1
```
